apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-30T16:08:08Z"
  labels:
    app: heimdall-pod
  name: heimdall-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8-8
    image: lscr.io/linuxserver/heimdall:latest
    name: heimdall
    ports:
    - containerPort: 443
      hostPort: 4431
    - containerPort: 80
      hostPort: 8081
    volumeMounts:
    - mountPath: /config
      name: heimdall-config
  volumes:
  - hostPath:
      path: /srv/containers/heimdall/config
      type: DirectoryOrCreate
    name: heimdall-config
