apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /srv/containers/jellyfin/config:Z
    io.containers.autoupdate: image
  creationTimestamp: "2024-05-17T21:08:34Z"
  labels:
    app: jellyfin-pod
  name: jellyfin-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: docker.io/jellyfin/jellyfin:latest
    name: jellyfin
    ports:
    - containerPort: 8096
      hostPort: 8096
    tty: true
    volumeMounts:
    - mountPath: /media
      name: samba-root
      readOnly: true
    - mountPath: /cache
      name: jellyfin-cache
    - mountPath: /config
      name: jellyfin-config
  volumes:
  - hostPath:
      path: /srv/containers/jellyfin/cache
      type: Directory
    name: jellyfin-cache
  - hostPath:
      path: /srv/containers/jellyfin/config
      type: Directory
    name: jellyfin-config
  - hostPath:
      path: /srv/samba
      type: Directory
    name: samba-root