apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /srv/containers/jellyfin/config:Z
    io.containers.autoupdate: image
  creationTimestamp: "2024-06-09T20:46:10.988287972Z"
  labels:
    app: jellyfinOne
  name: jellyfinOne
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: docker.io/jellyfin/jellyfin:latest
    name: jellyfinOne
    ports:
    - containerPort: 8096
      hostPort: 8096
    - containerPort: 8920
      hostPort: 8920
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /media
      name: samba-root
      readOnly: true
    - mountPath: /cache
      name: jellyfin-cache
    - mountPath: /config
      name: jellyfin-config
  volumes:
  - hostPath:
      path: /srv/containers/jellyfin/cache
      type: DirectoryOrCreate
    name: jellyfin-cache
  - hostPath:
      path: /srv/containers/jellyfin/config
      type: DirectoryOrCreate
    name: jellyfin-config
  - hostPath:
      path: /srv/samba
      type: Directory
    name: samba-root
