apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /srv/containers/jellyfin/cache:Z
  creationTimestamp: "2024-05-17T20:10:02Z"
  labels:
    app: media-pod
    io.containers.autoupdate: image
  name: media-pod
spec:
  containers:
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/sabnzbd:latest
    name: sabnzbd
    ports:
    - containerPort: 8080
      hostPort: 8080
    restart: unless-stopped
    volumeMounts:
    - mountPath: /downloads
      name: sabnzbd-downloads
    - mountPath: /incomplete-downloads
      name: sabnzbd-incomplete
    - mountPath: /jobs
      name: sabnzbd-jobs
    - mountPath: /config
      name: sabnzbd-config
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/prowlarr:latest
    name: prowlarr
    ports:
    - containerPort: 9696
      hostPort: 9696
    restart: unless-stopped      
    volumeMounts:
    - mountPath: /config
      name: prowlarr-config
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/sonarr:latest
    name: sonarr
    ports:
      - containerPort: 8989
        hostPort: 8989
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: sonarr-config
    - mountPath: /tv
      name: samba-tv
    - mountPath: /downloads
      name: sabnzbd-downloads
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/radarr:latest
    name: radarr
    ports:
    - containerPort: 7878
      hostPort: 7878
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: radarr-config
    - mountPath: /movies
      name: samba-movies
    - mountPath: /downloads
      name: sabnzbd-downloads
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/lidarr:latest
    name: lidarr
    ports:
    - containerPort: 8686
      hostPort: 8686 
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: lidarr-config
    - mountPath: /music
      name: samba-music
    - mountPath: /downloads
      name: sabnzbd-downloads
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/readarr:develop
    name: readarr
    ports:
    - containerPort: 8787
      hostPort: 8787
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: readarr-config
    - mountPath: /books
      name: samba-books
    - mountPath: /downloads
      name: sabnzbd-downloads
  - env:
    - name: LANG
      value: en_US.UTF-8
    - name: TZ
      value: America/New_York
    - name: PGID
      value: "1001"
    - name: LANGUAGE
      value: en_US.UTF-8
    - name: PUID
      value: "1001" 
    - name: JELLYFIN_PublishedServerUrl
      value: "192.168.2.79"
    image: docker.io/jellyfin/jellyfin:latest
    name: jellyfin
    ports:
    - containerPort: 8096
      hostPort: 8096
    - containerPort: 7359
      hostPort: 7359
    - containerPort: 1900
      hostPort: 1900
    restart: no
    volumeMounts:
    - mountPath: /config
      name: jellyfin-config
    - mountPath: /cache
      name: jellyfin-cache
    - mountPath: /tv
      name: samba-tv
    - mountPath: /movies
      name: samba-movies
  volumes:
  - hostPath:
      path: /srv/containers/sabnzbd/jobs
      type: Directory
    name: sabnzbd-jobs
  - hostPath:
      path: /srv/containers/sabnzbd/incomplete-downloads
      type: Directory
    name: sabnzbd-incomplete
  - hostPath:
      path: /srv/containers/sabnzbd/downloads
      type: Directory
    name: sabnzbd-downloads
  - hostPath:
      path: /srv/containers/sabnzbd/config
      type: Directory
    name: sabnzbd-config
  - hostPath:
      path: /srv/containers/lidarr/config
      type: Directory
    name: lidarr-config
  - hostPath:
      path: /srv/containers/prowlarr/config
      type: Directory
    name: prowlarr-config
  - hostPath:
      path: /srv/containers/radarr/config
      type: Directory
    name: radarr-config
  - hostPath:
      path: /srv/containers/readarr/config
      type: Directory
    name: readarr-config
  - hostPath:
      path: /srv/containers/sonarr/config
      type: Directory
    name: sonarr-config
  - hostPath:
      path: /srv/containers/jellyfin/config
      type: Directory
    name: jellyfin-config
  - hostPath:
      path: /srv/containers/jellyfin/cache
      type: Directory
    name: jellyfin-cache
  - hostPath:
      path: /srv/samba/tv
      type: Directory
    name: samba-tv
  - hostPath:
      path: /srv/samba/movies
      type: Directory
    name: samba-movies
  - hostPath:
      path: /srv/samba/music
      type: Directory
    name: samba-music
  - hostPath:
      path: /srv/samba/books
      type: Directory
    name: samba-books
