apiVersion: v1
kind: Pod
metadata:
  labels:
    app: media-pod
    io.containers.autoupdate: image
  name: media-pod
spec:
  containers:
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/sabnzbd:latest
    name: sabnzbd
    ports:
    - containerPort: 8080
      hostPort: 8080
    volumeMounts:
    - mountPath: /downloads
      name: sabnzbd-downloads
    - mountPath: /incomplete-downloads
      name: sabnzbd-incomplete
    - mountPath: /jobs
      name: sabnzbd-jobs
    - mountPath: /config
      name: sabnzbd-config
  - env:
    - name: PUID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: PGID
      value: "1001"
    image: docker.io/linuxserver/sonarr:latest
    name: sonarr
    ports:
      - containerPort: 8989
        hostPort: 8989
    volumeMounts:
    - mountPath: /config
      name: sonarr-config
    - mountPath: /tv
      name: samba-tv
    - mountPath: /downloads
      name: sabnzbd-downloads
  - env:
    - name: LANG
      value: en_US.UTF-8
    - name: TZ
      value: America/New_York
    - name: PGID
      value: "1001"
    - name: LANGUAGE
      value: en_US.UTF-8
    - name: PUID
      value: "1001"
    image: docker.io/linuxserver/radarr:latest
    name: radarr
    ports:
    - containerPort: 7878
      hostPort: 7878
    volumeMounts:
    - mountPath: /config
      name: radarr-config
    - mountPath: /movies
      name: samba-movies
    - mountPath: /downloads
      name: sabnzbd-downloads
  volumes:
  - hostPath:
      path: /srv/containers/sonarr/config
      type: Directory
    name: sonarr-config
  - hostPath:
      path: /srv/containers/radarr/config
      type: Directory
    name: radarr-config
  - hostPath:
      path: /srv/containers/sabnzbd/config
      type: Directory
    name: sabnzbd-config
  - hostPath:
      path: /srv/containers/sabnzbd/incomplete-downloads
      type: Directory
    name: sabnzbd-incomplete
  - hostPath:
      path: /srv/containers/sabnzbd/jobs
      type: Directory
    name: sabnzbd-jobs
  - hostPath:
      path: /srv/containers/sabnzbd/downloads
      type: Directory
    name: sabnzbd-downloads
  - hostPath:
      path: /srv/samba/tv
      type: Directory
    name: samba-tv
  - hostPath:
      path: /srv/samba/movies
      type: Directory
    name: samba-movies