apiVersion: v1
kind: Pod
metadata: 
  annotations:
    bind-mount-options: /srv/containers/jellyfin/config:Z
    bind-mount-options/media-pod-jellyfin: /srv/containers/jellyfin/config:Z
    io.containers.autoupdate/media-pod-jellyfin: image
    io.containers.autoupdate/media-pod-sabnzbd: image
    io.containers.autoupdate/media-pod-prowlarr: image
    io.containers.autoupdate/media-pod-radarr: image
    io.containers.autoupdate/media-pod-sonarr: image
    io.podman.annotations.kube.health.check/media-pod-jellyfin: "true"
    io.podman.annotations.kube.health.check/media-pod-sabnzbd: "true"
    io.podman.annotations.kube.health.check/media-pod-prowlarr: "true"
    io.podman.annotations.kube.health.check/media-pod-radarr: "true"
    io.podman.annotations.kube.health.check/media-pod-sonarr: "true"
  creationTimestamp: "2024-07-13T01:25:16Z"
  labels:
    app: media-pod
  name: media-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: docker.io/jellyfin/jellyfin:latest
    name: jellyfin
    ports:
    - containerPort: 8096 #HTTP Traffic
      hostPort: 8096
    - containerPort: 8920 #HTTPS Traffic
      hostPort: 8920
    - containerPort: 1900 #Service Discovery
      hostPort: 1900
    - containerPort: 7359 #Client Discovery
      hostPort: 7359
    restart: unless-stopped
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /sdcard
      name: sdcard
      readOnly: true
    - mountPath: /redbook
      name: redbook
      readOnly: true
    - mountPath: /m2
      name: m2
      readOnly: true
    - mountPath: /cache
      name: jellyfin-cache
    - mountPath: /config
      name: jellyfin-config
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/prowlarr:latest
    name: prowlarr
    ports:
    - containerPort: 9696
      hostPort: 9696
    restart: unless-stopped      
    volumeMounts:
    - mountPath: /config
      name: prowlarr-config
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/sabnzbd:latest
    name: sabnzbd
    ports:
    - containerPort: 8080
      hostPort: 8080
    restart: unless-stopped
    volumeMounts:
    - mountPath: /downloads
      name: sabnzbd-downloads
    - mountPath: /incomplete-downloads
      name: sabnzbd-incomplete
    - mountPath: /jobs
      name: sabnzbd-jobs
    - mountPath: /config
      name: sabnzbd-config
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/sonarr:latest
    name: sonarr
    ports:
      - containerPort: 8989
        hostPort: 8989
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: sonarr-config
    - mountPath: /downloads
      name: sabnzbd-downloads
    - mountPath: /sdcard
      name: sdcard
      readOnly: true
    - mountPath: /redbook
      name: redbook
      readOnly: true
    - mountPath: /m2
      name: m2
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/radarr:latest
    name: radarr
    ports:
    - containerPort: 7878
      hostPort: 7878
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: radarr-config
    - mountPath: /downloads
      name: sabnzbd-downloads
    - mountPath: /sdcard
      name: sdcard
      readOnly: true
    - mountPath: /redbook
      name: redbook
      readOnly: true
    - mountPath: /m2
      name: m2
  volumes:
  - hostPath:
      path: /srv/containers/sabnzbd/jobs
      type: DirectoryOrCreate
    name: sabnzbd-jobs
  - hostPath:
      path: /srv/containers/sabnzbd/incomplete-downloads
      type: DirectoryOrCreate
    name: sabnzbd-incomplete
  - hostPath:
      path: /srv/containers/sabnzbd/downloads
      type: DirectoryOrCreate
    name: sabnzbd-downloads
  - hostPath:
      path: /srv/containers/sabnzbd/config
      type: DirectoryOrCreate
    name: sabnzbd-config
  - hostPath:
      path: /srv/containers/prowlarr/config
      type: DirectoryOrCreate
    name: prowlarr-config
  - hostPath:
      path: /srv/containers/radarr/config
      type: DirectoryOrCreate
    name: radarr-config
  - hostPath:
      path: /srv/containers/sonarr/config
      type: DirectoryOrCreate
    name: sonarr-config
  - hostPath:
      path: /srv/containers/jellyfin/config
      type: DirectoryOrCreate
    name: jellyfin-config
  - hostPath:
      path: /srv/containers/jellyfin/cache
      type: DirectoryOrCreate
    name: jellyfin-cache
  - hostPath:
      path: /mnt/m2
      type: Directory
    name: m2
  - hostPath:
      path: /mnt/sd
      type: Directory
    name: sdcard
  - hostPath:
      path: /mnt/redbook
      type: Directory
    name: redbook
