apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/media-jellyfin: image
    io.containers.autoupdate/media-sabnzbd: image
    io.containers.autoupdate/media-prowlarr: image
    io.containers.autoupdate/media-lidarr: image
    io.containers.autoupdate/media-radarr: image
    io.containers.autoupdate/media-readarr: image
    io.containers.autoupdate/media-sonarr: image
    io.containers.autoupdate/media-heimdall: image
    io.podman.annotations.kube.health.check/media-jellyfin: "true"
    io.podman.annouiop34.tations.kube.health.check/media-sabnzbd: "true"
    io.podman.annotations.kube.health.check/media-prowlarr: "true"
    io.podman.annotations.kube.health.check/media-lidarr: "true"
    io.podman.annotations.kube.health.check/media-radarr: "true"
    io.podman.annotations.kube.health.check/media-readarr: "true"
    io.podman.annotations.kube.health.check/media-sonarr: "true"
    io.podman.annotations.kube.health.check/media-heimdall: "true"
  creationTimestamp: "2024-07-30T16:08:08Z"
  labels:
    app: media
  name: media
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/jellyfin/jellyfin:latest
    name: jellyfin
    group_add:
    - render #getent group render | cut -d: -f3
    ports:
    - containerPort: 8096 #HTTP Traffic
      hostPort: 8096
    - containerPort: 8920 #HTTPS Traffic
      hostPort: 8920
    - containerPort: 1900 #Service Discovery
      hostPort: 1900
    - containerPort: 7359 #Client Discovery
      hostPort: 7359
    tty: true
    volumeMounts:
    - mountPath: /sdcard
      name: sdcard
    - mountPath: /redbook
      name: redbook
    - mountPath: /m2
      name: m2
    - mountPath: /cache
      name: jellyfin-cache
    - mountPath: /config
      name: jellyfin-config
    - mountPath: /dev/dri/renderD128
      name: render-device
    - mountPath: /dev/dri/card0
      name: render-card
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/sabnzbd:latest
    name: sabnzbd
    ports:
    - containerPort: 8080
      hostPort: 8080
    volumeMounts:
    - mountPath: /downloads
      name: sabnzbd-downloads
    - mountPath: /incomplete-downloads
      name: sabnzbd-incomplete
    - mountPath: /jobs
      name: sabnzbd-jobs
    - mountPath: /config
      name: sabnzbd-config
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/prowlarr:latest
    name: prowlarr
    ports:
    - containerPort: 9696
      hostPort: 9696
    volumeMounts:
    - mountPath: /config
      name: prowlarr-config
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/lidarr:latest
    name: lidarr
    ports:
    - containerPort: 8686
      hostPort: 8686
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: lidarr-config
    - mountPath: /music
      name: samba-music
    - mountPath: /downloads
      name: sabnzbd-downloads
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/sonarr:latest
    name: sonarr
    ports:
    - containerPort: 8989
      hostPort: 8989
    volumeMounts:
    - mountPath: /config
      name: sonarr-config
    - mountPath: /downloads
      name: sabnzbd-downloads
    - mountPath: /sdcard
      name: sdcard
    - mountPath: /redbook
      name: redbook
    - mountPath: /m2
      name: m2
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/radarr:latest
    name: radarr
    ports:
    - containerPort: 7878
      hostPort: 7878
    volumeMounts:
    - mountPath: /config
      name: radarr-config
    - mountPath: /downloads
      name: sabnzbd-downloads
    - mountPath: /sdcard
      name: sdcard
    - mountPath: /redbook
      name: redbook
    - mountPath: /m2
      name: m2
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/readarr:develop
    name: readarr
    ports:
    - containerPort: 8787
      hostPort: 8787
    volumeMounts:
    - mountPath: /config
      name: readarr-config
    - mountPath: /books
      name: samba-books
    - mountPath: /downloads
      name: sabnzbd-downloads
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: lscr.io/linuxserver/heimdall:latest
    name: heimdall
    ports:
    - containerPort: 8081
      hostPort: 80
    volumeMounts:
    - mountPath: /config
      name: heimdall-config
  restartPolicy: Always
  volumes:
  - hostPath:
    - hostPath:
      path: /mnt/m2
      type: Directory
    name: m2
  - hostPath:
      path: /mnt/sd
      type: Directory
    name: sdcard
  - hostPath:
      path: /mnt/redbook
      type: Directory
    name: redbook
      path: /mnt/sd/music
      type: DirectoryOrCreate
    name: samba-music
  - hostPath:
      path: /mnt/sd/books
      type: DirectoryOrCreate
    name: samba-books
  - hostPath:
      path: /srv/containers/sabnzbd/config
      type: DirectoryOrCreate
    name: sabnzbd-config
  - hostPath:
      path: /srv/containers/sabnzbd/jobs
      type: DirectoryOrCreate
    name: sabnzbd-jobs
  - hostPath:
      path: /srv/containers/sabnzbd/incomplete-downloads
      type: DirectoryOrCreate
    name: sabnzbd-incomplete
  - hostPath:
      path: /srv/containers/sabnzbd/downloads
      type: DirectoryOrCreate
    name: sabnzbd-downloads
  - hostPath:
      path: /srv/containers/prowlarr/config
      type: DirectoryOrCreate
    name: prowlarr-config
  - hostPath:
      path: /srv/containers/lidarr/config
      type: DirectoryOrCreate
    name: lidarr-config
  - hostPath:
      path: /srv/containers/radarr/config
      type: DirectoryOrCreate
    name: radarr-config
  - hostPath:
      path: /srv/containers/readarr/config
      type: DirectoryOrCreate
    name: readarr-config
  - hostPath:
      path: /srv/containers/sonarr/config
      type: DirectoryOrCreate
    name: sonarr-config
  - hostPath:
      path: /srv/containers/heimdall/config
      type: DirectoryOrCreate
    name: heimdall-config
  - hostPath:
      path: "/dev/dri/renderD128"
      type: Directory
    name: "render-device"
  - hostPath:
      path: "/dev/dri/card0"
      type: Directory
    name: "render-card"
  - hostPath:
      path: /srv/containers/jellyfin/config
      type: DirectoryOrCreate
    name: jellyfin-config
  - hostPath:
      path: /srv/containers/jellyfin/cache
      type: DirectoryOrCreate
    name: jellyfin-cache

