apiVersion: v1
kind: Pod
metadata: 
  annotations:
    bind-mount-options: /srv/containers/jellyfin/config:Z
    bind-mount-options/mediaPod-jellyfin: /srv/containers/jellyfin/config:Z
    bind-mount-options/mediaPod-lidarr: /srv/containers/jellyfin/config:Z
    bind-mount-options/mediaPod-prowlarr: /srv/containers/jellyfin/config:Z
    bind-mount-options/mediaPod-radarr: /srv/containers/jellyfin/config:Z
    bind-mount-options/mediaPod-readarr: /srv/containers/jellyfin/config:Z
    bind-mount-options/mediaPod-sabnzbd: /srv/containers/jellyfin/config:Z
    bind-mount-options/mediaPod-sonarr: /srv/containers/jellyfin/config:Z
    io.containers.autoupdate/mediaPod-jellyfin: image
    io.containers.autoupdate/mediaPod-lidarr: image
    io.containers.autoupdate/mediaPod-prowlarr: image
    io.containers.autoupdate/mediaPod-radarr: image
    io.containers.autoupdate/mediaPod-readarr: image
    io.containers.autoupdate/mediaPod-sabnzbd: image
    io.containers.autoupdate/mediaPod-sonarr: image
    io.podman.annotations.kube.health.check/mediaPod-jellyfin: "true"
    io.podman.annotations.kube.health.check/mediaPod-lidarr: "true"
    io.podman.annotations.kube.health.check/mediaPod-prowlarr: "true"
    io.podman.annotations.kube.health.check/mediaPod-radarr: "true"
    io.podman.annotations.kube.health.check/mediaPod-readarr: "true"
    io.podman.annotations.kube.health.check/mediaPod-sabnzbd: "true"
    io.podman.annotations.kube.health.check/mediaPod-sonarr: "true"
  creationTimestamp: "2024-06-16T15:55:45Z"
  labels:
    app: mediaPod
  name: mediaPod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: docker.io/jellyfin/jellyfin:latest
    name: jellyfin
    ports:
    - containerPort: 8096 #HTTP Traffic
      hostPort: 8096
    - containerPort: 8920 #HTTPS Traffic
      hostPort: 8920
    - containerPort: 1900 #Service Discovery
      hostPort: 1900
    - containerPort: 7359 #Client Discovery
      hostPort: 7359
    restart: unless-stopped
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /media
      name: samba-root
      readOnly: true
    - mountPath: /cache
      name: jellyfin-cache
    - mountPath: /config
      name: jellyfin-config
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/prowlarr:latest
    name: prowlarr
    ports:
    - containerPort: 9696
      hostPort: 9696
    restart: unless-stopped      
    volumeMounts:
    - mountPath: /config
      name: prowlarr-config
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/sabnzbd:latest
    name: sabnzbd
    ports:
    - containerPort: 8080
      hostPort: 8080
    restart: unless-stopped
    volumeMounts:
    - mountPath: /downloads
      name: sabnzbd-downloads
    - mountPath: /incomplete-downloads
      name: sabnzbd-incomplete
    - mountPath: /jobs
      name: sabnzbd-jobs
    - mountPath: /config
      name: sabnzbd-config
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/sonarr:latest
    name: sonarr
    ports:
      - containerPort: 8989
        hostPort: 8989
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: sonarr-config
    - mountPath: /tv
      name: samba-tv
    - mountPath: /downloads
      name: sabnzbd-downloads
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/radarr:latest
    name: radarr
    ports:
    - containerPort: 7878
      hostPort: 7878
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: radarr-config
    - mountPath: /movies
      name: samba-movies
    - mountPath: /downloads
      name: sabnzbd-downloads
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/lidarr:latest
    name: lidarr
    ports:
    - containerPort: 8686
      hostPort: 8686 
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: lidarr-config
    - mountPath: /music
      name: samba-music
    - mountPath: /downloads
      name: sabnzbd-downloads
  - env:
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8
    image: docker.io/linuxserver/readarr:develop
    name: readarr
    ports:
    - containerPort: 8787
      hostPort: 8787
    restart: unless-stopped
    volumeMounts:
    - mountPath: /config
      name: readarr-config
    - mountPath: /books
      name: samba-books
    - mountPath: /downloads
      name: sabnzbd-downloads
  volumes:
  - hostPath:
      path: /srv/containers/sabnzbd/jobs
      type: Directory
    name: sabnzbd-jobs
  - hostPath:
      path: /srv/containers/sabnzbd/incomplete-downloads
      type: Directory
    name: sabnzbd-incomplete
  - hostPath:
      path: /srv/containers/sabnzbd/downloads
      type: Directory
    name: sabnzbd-downloads
  - hostPath:
      path: /srv/containers/sabnzbd/config
      type: Directory
    name: sabnzbd-config
  - hostPath:
      path: /srv/containers/lidarr/config
      type: Directory
    name: lidarr-config
  - hostPath:
      path: /srv/containers/prowlarr/config
      type: Directory
    name: prowlarr-config
  - hostPath:
      path: /srv/containers/radarr/config
      type: Directory
    name: radarr-config
  - hostPath:
      path: /srv/containers/readarr/config
      type: Directory
    name: readarr-config
  - hostPath:
      path: /srv/containers/sonarr/config
      type: Directory
    name: sonarr-config
  - hostPath:
      path: /srv/containers/jellyfin/config
      type: DirectoryOrCreate
    name: jellyfin-config
  - hostPath:
      path: /srv/containers/jellyfin/cache
      type: DirectoryOrCreate
    name: jellyfin-cache
  - hostPath:
      path: /srv/samba/tv
      type: Directory
    name: samba-tv
  - hostPath:
      path: /srv/samba/movies
      type: Directory
    name: samba-movies
  - hostPath:
      path: /srv/samba/music
      type: Directory
    name: samba-music
  - hostPath:
      path: /srv/samba/books
      type: Directory
    name: samba-books
  - hostPath:
      path: /srv/samba
      type: Directory
    name: samba-root