version: "3.x"
services:
  swag:
    image: lscr.io/linuxserver/swag
    name: swag
    environment:
      TERM: xterm
      PUID: "1001"
      PGID: "1001"
      TZ: America/New_York
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      URL: superflea.duckdns.org
      SUBDOMAINS: wildcard
      VALIDATION: duckdns
      EMAIL: stephen.ancliffe@gmail.com
      DUCKDNSTOKEN: ${DUCKDNS_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      swag-config:
        type: directory
        source: /srv/containers/swag/config
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  volumes:
    swag-config:  
      type: none
      bind:
        source: /srv/containers/swag/config
        destination: /config