---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-09-06T22:10:29Z"
  labels:
    app: swag
  name: swag
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US.UTF-8-8
    - name: URL
      value: superflea.duckdns.org
    - name: SUBDOMAINS
      value: wildcard
    - name: VALIDATION
      value: duckdns
    - name: EMAIL
      value: stephen.ancliffe@gmail.com
    - name: DUCKDNSTOKEN
      value: ${DUCKDNS_TOKEN}
    image: lscr.io/linuxserver/swag
    name: swag
    ports:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443
    volumeMounts:
    - mountPath: /config
      name: swag-config
    cap_add:
      - NET_ADMIN
  volumes:
  - hostPath:
      path: /srv/containers/swag/config
      type: DirectoryOrCreate
    name: swag-config

    restart: unless-stopped