---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - URL=superflea.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
    volumes:
      - /srv/containers/swag/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped