apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-09-07T13:45:56Z"
  labels:
    app: swag
  name: swag
spec:
  containers:
  - env:
    - name: SUBDOMAINS
      value: wildcard
    - name: DUCKDNSTOKEN
      valueFrom:
        secretKeyRef:
          name: my-kube-password
          key: password
    - name: URL
      value: superflea.duckdns.org
    - name: PUID
      value: "1001"
    - name: EMAIL
      value: stephen.ancliffe@gmail.com
    - name: LANGUAGE
      value: en_US.UTF-8-8
    - name: LANG
      value: en_US.UTF-8
    - name: VALIDATION
      value: duckdns
    - name: PGID
      value: "1001"
    - name: TZ
      value: America/New_York
    image: lscr.io/linuxserver/swag:latest
    name: swag
    ports:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443
    volumeMounts:
    - mountPath: /config
      name: swag-config
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /srv/containers/swag/config
      type: Directory
    name: swag-config

