apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /srv/containers/jellyfin/config:Z
    io.containers.autoupdate: image
  creationTimestamp: "2024-06-16T15:55:45Z"
  labels:
    app: jellyPod
  name: jellyPod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: docker.io/jellyfin/jellyfin:latest
    name: jellyfin
    ports:
    - containerPort: 8096 #HTTP Traffic
      hostPort: 8096
    - containerPort: 8920 #HTTPS Traffic
      hostPort: 8920
    - containerPort: 1900 #Service Discovery
      hostPort: 1900
    - containerPort: 7359 #Client Discovery
      hostPort: 7359
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /media
      name: samba-root
      readOnly: true
    - mountPath: /cache
      name: jellyfin-cache
    - mountPath: /config
      name: jellyfin-config
  volumes:
  - hostPath:
      path: /srv/containers/jellyfin/cache
      type: DirectoryOrCreate
    name: jellyfin-cache
  - hostPath:
      path: /srv/containers/jellyfin/config
      type: DirectoryOrCreate
    name: jellyfin-config
  - hostPath:
      path: /srv/samba
      type: Directory
    name: samba-root
