# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.2.1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
  creationTimestamp: "2024-08-23T21:40:12Z"
  name: jellyfin-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
